### ISSUE TITLE
Download option not available for the selected song.

### ISSUE THREAD

**Issue by rajatnt** [alashow/datmusicbot#3]
I have setup the bot. The inline queries are working fine and am able to select the songs suggested but as i select the songs, download option is not shown and a red exclamation flag is shown in left bottom corner of the result. Have uploaded the image [here](https://imgur.com/a/7BuqS) : https://imgur.com/a/7BuqS .
Don't know if this is issue in the api server or the bot itself.
Please suggest What am I missing?

**Comment by alashow** [comment]
Did you see your API's logs? Probably it's not giving mp3s to Telegram.
